### ISSUE TITLE
与最新版本的Unity支付存在冲突。

### ISSUE THREAD

**Issue by 0x7cc** [MobClub/New-Unity-For-ShareSDK#27]
最近使用unity支付的项目，总是弹出升级窗口，点击升级后，与shareSDK存在类名冲突，以下是我看见的报错：
Assets/ShareSDKiOSAutoPackage/Editor/SDKPorter/XCodeEditor/XCMod.cs(106,37): error CS0234: The type or namespace name `jsonDecode' does not exist in the namespace `MiniJSON'. Are you missing an assembly reference?
其实Demo.cs也存在这样的冲突，只是我删掉了。

**Comment by liufangli520** [comment]
> 最近使用unity支付的项目，总是弹出升级窗口，点击升级后，与shareSDK存在类名冲突，以下是我看见的报错：
> Assets/ShareSDKiOSAutoPackage/Editor/SDKPorter/XCodeEditor/XCMod.cs(106,37): error CS0234: The type or namespace name `jsonDecode' does not exist in the namespace `MiniJSON'. Are you missing an assembly reference?
> 其实Demo.cs也存在这样的冲突，只是我删掉了。

demo.cs只是我们的例子的脚本，您可以不用导入自己的项目，可以参考这个来调用接口而已

**Comment by 0x7cc** [comment]
三年前的问题了哈哈哈哈
