### ISSUE TITLE
微信登陆授权后返回自己APP界面的时候卡死了……

### ISSUE THREAD

**Issue by luoyuan800** [MobClub/New-Unity-For-ShareSDK#36]
求助！！！Unity 2017 .1 的版本接入sdk， 调用GetUserInfo后会进入到微信的界面，点击登陆后，返回自己app的界面的时候就会程序卡死，新建了一个页面，用你们的demo.cs 也会同样卡死。 用的是魅族手机，Android系统 6.0。
我已经重新打包过那个demo.jar， 改过里面的包路径为自己的路径了，其他配置应该都不会有错的。

**Comment by moblarry** [comment]
是个别机型才会吗?Demo跑完打包之后可以的吗，可以用我们签名文件签名测试Demo，密码是123456

**Comment by WatchMan-Wang** [comment]
这个DemoCallback.jar包你可以联系对官方技术支持帮你打个，或者你可以将你自己打的jar包发给他们，让他们帮忙检查下。
