### ISSUE TITLE
Android Export出来Gradle项目，报错Error: Program type already present: com.jimu52.mailcat.BuildConfig

### ISSUE THREAD

**Issue by tpnet** [MobClub/New-Unity-For-ShareSDK#42]
![image](https://user-images.githubusercontent.com/17380722/69143430-eac7ee00-0b03-11ea-915b-93495dfad143.png)

**Comment by tpnet** [comment]
在AndroidStudio build 项目的时候报错

**Comment by marvinguo** [comment]
怎么解决的呢？是新版本的问题吗？

**Comment by tpnet** [comment]
@marvinguo 打包出来的项目的ShareSdk的module的manifest的包名不要和项目一样

**Comment by jie0713** [comment]
您联系一下mob官方Q：4006852216 具体有技术支持帮您解答
